services:
  uploadapp:
    image: uploadpipeline:latest
    env_file:
      - secrets/.env
    ports:
      - 8501:8501
    volumes:
      - /mnt/d-drive/micro/Documents/GitHub/uploadapp/data:/uploadapp/data