services:
  uploadapp:
    image: uploadapp:latest
    env_file:
      - secrets/.env
    ports:
      - 5000:8000
    volumes:
      - /mnt/d-drive/micro/Documents/GitHub/uploadapp/data:/uploadapp/data
      - /mnt/d-drive/micro/Documents/GitHub/uploadapp/processing:/uploadapp/processing
